### ISSUE TITLE
List of final Todo's

### ISSUE THREAD

**Issue by codetony25** [codetony25/lottogopher-emails#6]
- [ ] Fix alignment of icons
![Uploading Screen Shot 2017-04-20 at 9.29.36 AM.png…]()

- [ ] Add missing images on footer
![screen shot 2017-04-20 at 9 35 33 am](https://cloud.githubusercontent.com/assets/10192761/25242007/ee76865e-25ac-11e7-8fff-486a9c098436.png)
<img width="362" alt="screen shot 2017-04-20 at 9 35 28 am" src="https://cloud.githubusercontent.com/assets/10192761/25242010/f0d4b31c-25ac-11e7-8007-838f0291c8fe.png">
 
- [ ] Try to make buttons an entire link (clickable) or a majority of the button
